---
title: "Week 19"
output: html_notebook
---

This is a document to play with week 19 tidy tuesday dataset.

```{r load_data}

tuesdaydata <- tidytuesdayR::tt_load('2021-05-04')

water <- tuesdaydata$water

```

Explore Dataset

```{r Explore}

library(tidyverse)
library(lubridate)

#glimpse(water)

#DataExplorer::create_report(water)

fact_cols <- c("status_id", "water_source", "water_tech", "facility_type", "country_name")


# Convert columns to appropriate type

water <- water %>% mutate(across(fact_cols, as_factor), 
                          report_date = mdy(report_date))

```


Plot water points on basic map

```{r map}

water %>% ggplot(aes(lon_deg, lat_deg)) + 
  geom_point(size = .25, show.legend = FALSE) +
  coord_quickmap()

#ind <- map_data("world") %>% filter(region %in% c("Kenya", "Namibia", "South Africa", "Egypt"))

#ggplot() +
#  geom_polygon(data = ind, aes(x = long, y = lat, group = group), fill="lightgray", colour = "white") + 
#  geom_point(data = water, aes(lon_deg, lat_deg), size = 0.25) + theme_bw()

```


Interactive Brushing

```{r Brushing_Bars}

library(patchwork)
library(ggiraph)

var_list <- c('status_id', 'water_source', 'water_tech', 'facility_type', 'country_name')


gen_bar <- function(var, brush_var){
  ggplot(water) + geom_bar_interactive(aes(fct_rev(fct_infreq(!!sym(var))), 
                                       data_id = !!sym(brush_var),
                                       tooltip = !!sym(brush_var))) +
    labs(title = var) +
    xlab(NULL) +
    theme(axis.text.x = element_text(size = 1)) +
    coord_flip()
}

g <- map(var_list, ~gen_bar(var = ., brush_var = 'status_id'))

bplot <- g[[1]] + g[[2]] +g[[3]] + g[[4]] + g[[5]] + plot_layout(ncol = 2)

int_g <- girafe(ggobj = bplot)

int_g <- girafe_options(int_g, opts_sizing(rescale = FALSE))

int_g

```

Interactivity works as expected, but the x-labels are too long that obscures the graph completely. Need a way to control the size of x labels.



Line Charts by Year

```{r Line Charts}

library(ggiraph)

country_year <- water %>% group_by(country_name, install_year) %>% 
  summarise(number_of_points = n()) %>% ungroup() %>% drop_na(c(country_name, install_year))


g <- country_year %>% ggplot(aes(install_year, number_of_points)) + geom_line_interactive(aes(tooltip = country_name, color = country_name, data_id = country_name)) + 
  ylim(c(0, 8000)) + guides(color = FALSE) + 
  #facet_wrap(~status_id) +
  theme_minimal()

g1 <- girafe(ggobj = g)

g1 <- girafe_options(g1, 
               opts_tooltip(opacity = 0.7),
               opts_hover(css = "stroke:red;opacity = 1;"),
               opts_hover_inv(css = "stroke:grey; opacity = 0.01;"))

if (interactive()) print(g1)

```



Cumulative line chart Animation

```{r cumulative line chart}

library(gganimate)

country_year_cum <- country_year %>% group_by(country_name) %>% 
  mutate(cum_installs = cumsum(number_of_points)) %>% ungroup() %>% filter(install_year <= 2021)

top_countries <-country_year_cum %>% 
  group_by(country_name) %>% 
  slice_tail() %>% 
  arrange(-cum_installs) %>%
  ungroup() %>% 
  slice_head(n = 5)


top_country_cum <- country_year_cum %>% 
  semi_join(top_countries, by = "country_name")


g <- top_country_cum %>% ggplot(aes(install_year, cum_installs, color = country_name)) + 
  geom_line(size = 1) +
  geom_point(size = 2) + 
  ggrepel::geom_text_repel(aes(label = country_name)) +
  guides(color = "none") + 
  transition_reveal(install_year)

animate(g, renderer = gifski_renderer(file = here::here("Week 19 - Water", "Output", "Animation.gif"), loop = FALSE))


```



Bar Chart Animation

```{r Bar Chart Animation}

library(gganimate)


top_country_cum1 <- top_country_cum %>% 
  mutate(year = ceiling(install_year/10) * 10) %>%
  group_by(country_name, year) %>% 
  slice_tail() %>% 
  filter(year <= 2020) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(rank = as_factor(rank(cum_installs, ties.method = "first"))) %>% 
  ungroup()

top_country_cum1 %>% 
  ggplot(aes(cum_installs, rank), group = country_name) + 
  geom_col(aes(fill = country_name)) + 
  geom_text(
    aes(x = -200, label = country_name),
    hjust = 1, size = 14/.pt
  ) +
  labs(title = "Year: {closest_state}", y = "Country") +
  guides(fill = "none") +
  #gghighlight::gghighlight(country_name == "Uganda") +
  theme_minimal() +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank()
  ) +
  transition_states(year, transition_length = 10, state_length = 100, wrap = FALSE)

animate(g, renderer = gifski_renderer(file = here::here("Week 19 - Water", "Output", "Animation_Bar.gif"), loop = FALSE))


```




```{r}
top_country_cum1 %>% 
  filter(year == 1980) %>% 
  ggplot(aes(cum_installs, rank)) + 
  geom_col(aes(fill = country_name)) + 
  labs(title = "Year: {closest_state}", y = "Country") 
  #gghighlight::gghighlight(country_name == "Uganda")

```

